import {Employee} from "@/components/MaterialUITable";

export const data: Employee[] = [
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },{
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
  {
    name: "Username",
    status: "Working",
    role: "Product Manager",
    email: "username@company.com",
    teams: ["Design", "Product", "Development", "a", "b", "c", "d", "e"],
    avatar: "/Avatr.jpeg",
  },
]


